---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-admin-k8s-deployment
spec:
  selector:
    matchLabels:
      app: prod-admin-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: prod-admin-k8s
    spec:
      containers:
        - name: prod-admin-k8s
          image: registry.digitalocean.com/resty-registry/admin:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: prod-admin-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
