---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-admin-k8s-deployment
spec:
  selector:
    matchLabels:
      app: ngx-admin-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: ngx-admin-k8s
    spec:
      containers:
        - name: ngx-admin-k8s
          image: registry.digitalocean.com/resty-registry/ngx-admin:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ngx-admin-service
spec:
  selector:
    app: ngx-admin-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
