name: Deploy to DEV

#on: [push]
on:
  push:
    branches:
      - dev

env:
  REGISTRY: "registry.digitalocean.com/resty-registry"
  NGX_ADMIN: "ngx-admin"

jobs:
  deploy:
    name: Build API image
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: executing git pull on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: resty
          key: ${{ secrets.SSHKEY }}
          port: 22
          command_timeout: 30m
          envs: NGX_ADMIN,GITHUB_SHA,REGISTRY
          script: |
            cd /home/resty/admin
            git fetch
            git checkout dev
            git pull
            docker system prune -f --volumes
            docker build --no-cache -f src/Dockerfile.dev -t $(echo $REGISTRY)/$(echo $NGX_ADMIN):latest .

            doctl registry login
            docker push $(echo $REGISTRY)/$(echo $NGX_ADMIN):latest


            kubectl delete --f k8s/ngx-admin.k8s.yaml
            kubectl delete --f k8s/cloudflared.admin.yaml
            kubectl apply -f k8s/cloudflared.admin.yaml
            kubectl apply -f k8s/ngx-admin.k8s.yaml
