name: Deploy to Prod

#on: [push]
on:
  push:
    branches:
      - main

env:
  REGISTRY: "registry.digitalocean.com/resty-registry"
  NGX_ADMIN: "prod-admin"

jobs:
  deploy:
    name: Build Admin image
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: executing git pull on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: resty
          key: ${{ secrets.SSHKEY }}
          port: 22
          command_timeout: 30m
          envs: NGX_ADMIN,GITHUB_SHA,REGISTRY
          script: |
            cd /home/resty/admin
            git fetch
            git checkout main
            git pull
            docker system prune -f --volumes
            docker build --no-cache -f Dockerfile -t $(echo $REGISTRY)/$(echo $NGX_ADMIN):latest .

            doctl registry login
            docker push $(echo $REGISTRY)/$(echo $NGX_ADMIN):latest

            cd /home/resty/k8s
            kubectl apply -f cloudflared.yaml
            cd /home/resty/admin
            kubectl apply -f admin.k8s.yaml
            kubectl rollout restart deployment prod-admin-k8s-deployment
